# Generated by Django 6.1 on 2026-08-29 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='fecha de publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica_text', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro')),
            ],
        ),
    ]
