# Generated by Django 6.1 on 2026-09-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='votos',
        ),
    ]
