# Generated by Django 6.1 on 2026-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_remove_caracteristica_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
