# Generated by Django 6.1 on 2026-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_carro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='anio',
            field=models.IntegerField(default=2026),
        ),
    ]
